### ISSUE TITLE
Improve BLOB representation

### ISSUE THREAD

**Issue by JonatanPlesko** [infinum/android_dbinspector#63]
## :warning: Please describe your feature request
Currently, all BLOBs are displayed as (data). This is not a very descriptive representation of the stored data.

## :bulb: Describe the solution you'd like
A simple improvement would be to show all BLOBs as a hex string. This would help with data types such as byte arrays.
An advanced improvement would be showing different representation based on the BLOB type. For example, images could be rendered within the cell - possibly initially as a thumbnail with an option to expand.

## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

**Comment by bojankoma** [comment]
@JonatanPlesko Can you please provide a database with a several BLOBs inside? I'm having a hard time finding an example database to use as base to work on. Private channels will do fine too in case of sensitive data.

**Comment by bojankoma** [comment]
Basically, I've implemented this feature, but without inline and automatic preview inside a row cell.
Instead, you can now tap on the blob and if it is a supported image format (JPG, PNG, BMP) then a preview dialog will show with option to share the image.
In case of a text cell type - you can tap on the cell to get a similar preview and options.
I expect more feedback and feature expansion building upon this BLOB support as the demand rises.

**Comment by JonatanPlesko** [comment]
@bojankoma what about a HEX representation of binary data? I still have the issue where I want to debug some ByteArray data in my database, but it just shows `[ DATA ]` and I can't in any way access the underlying bytes.

**Comment by JonatanPlesko** [comment]
Never mind, I saw the Settings options now 🙂 let's update readme though!
